# Generated by Django 4.2 on 2023-04-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning', '0004_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_image')),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
    ]
