# Generated by Django 4.2 on 2023-04-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning', '0006_aboutimage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('courses_count', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='category_image')),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
